# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  remix-lib:
    docker:
        - image: circleci/node:7.10
    environment:
    working_directory: ~/repo
    steps:
      - checkout
      - run: cd remix-lib && npm install && npm test
            
  remix-core:
    docker:
        - image: circleci/node:7.10
    environment:
    working_directory: ~/repo
    steps:
      - checkout
      - run: cd remix-core && npm install && npm test
            
  remix-solidity:
    docker:
        - image: circleci/node:7.10
    environment:
    working_directory: ~/repo
    steps:
      - checkout
      - run: cd remix-solidity && npm install && npm run linkremixcore && npm run linkremixlib && npm install && npm test
      
  remix-debugger:
    docker:
        - image: circleci/node:7.10
    environment:
    working_directory: ~/repo
    steps:
      - checkout
      - run: cd remix-debugger && npm install && npm run linkremixlib && npm run linkremixcore && npm run linkremixsolidity && npm install &&  npm test
            
workflows:
  version: 2
  build_all:
    jobs:
      - remix-lib
      - remix-core
      - remix-solidity
      - remix-debugger
